# Copyright (C) 2020 Maxime Robeyns <maximerobeyns@gmail.com>

name: Project build and test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Compile and test
    steps:
    - uses: actions/checkout@v2
    - name: prepare container for tests
      run: sudo apt-get install -y make g++ python3-dev libpython3-dev
    - name: compile tests
      run: make test
    - name: run tests
      run: ./bin/optk_tests
