# Copyright (C) 2020 Maxime Robeyns <maximerobeyns@gmail.com>

name: Project build and test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Compile and test
    steps:
    - uses: actions/checkout@v2
    - name: compile tests
      run: make test
    - name: run tests
      run: ./bin/optk_tests
